server:
  port: 6801
spring:
    datasource:
        url: jdbc:mysql://192.168.1.105:3306/leilei?useUnicode=true&characterEncoding=UTF-8
        username: tang
        password: tangtang
        driver-class-name: com.mysql.jdbc.Driver
